### ISSUE TITLE
Test suite depends on hierarchical-clustering, which doesn't support GHC 7.10

### ISSUE THREAD

**Issue by snoyberg** [kaizhang/clustering#2]
For Stackage, I'm going to disable tests of clustering for now.

**Comment by bergmark** [comment]
This also applies to GHC 8, but HList is the problem there. The dependency chain is clustering -> RLang-QQ -> HList.

**Comment by kaizhang** [comment]
fixed in 4b6f2f4acb700637db5083a89e9a9d5b1e631200
